# Generated by Django 4.1.2 on 2022-10-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
