# Generated by Django 4.1.2 on 2022-10-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_alter_savings_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='balance',
            field=models.CharField(default=0.0, max_length=100),
        ),
    ]
