# Generated by Django 4.1.2 on 2022-10-13 11:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_savings_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='balance',
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('balance', models.CharField(default=0.0, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.savings')),
            ],
        ),
    ]
