# Generated by Django 4.1.2 on 2022-10-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0008_alter_balance_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='paid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.savings'),
        ),
    ]
