# Generated by Django 4.1.2 on 2022-10-13 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0009_alter_balance_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='paid',
        ),
        migrations.AddField(
            model_name='balance',
            name='amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savings.savings'),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
