# Generated by Django 4.1.2 on 2022-10-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0010_remove_balance_paid_balance_amount_balance_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='amount',
            new_name='paid',
        ),
    ]
