# Generated by Django 4.1.2 on 2022-10-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0011_rename_amount_balance_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
