# Generated by Django 4.1.2 on 2022-10-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0015_balance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='user',
        ),
    ]
