# Generated by Django 4.1.2 on 2022-10-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0016_remove_balance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savings.savings'),
        ),
    ]
