# Generated by Django 4.1.2 on 2022-10-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0019_alter_balance_paid_alter_balance_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
