# Generated by Django 4.1.2 on 2022-10-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0024_alter_balance_id_alter_savings_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='paid',
        ),
    ]
