# Generated by Django 4.1.2 on 2022-10-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0036_rename_amount_amount_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
