# Generated by Django 3.1 on 2023-01-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0037_amount_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savings',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='amount',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
