# Generated by Django 4.1.5 on 2023-01-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0038_auto_20230103_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
